const BUTTON_UPDATE_INTERVAL_DELAY = 500;
const BUTTON_INCREMENT_DELAY = 1;
const LOWEST_ENERGY_LEVEL = 0;
const LOWEST_DEGENERACY = 1;
const LOWEST_TEMPERATURE = 0;
const LOWEST_LEVEL_COUNT = 2;
const HIGHEST_ENERGY_LEVEL = 4;
const HIGHEST_DEGENERACY = 5;
const HIGHEST_TEMPERATURE = 1000;
const HIGHEST_LEVEL_COUNT = 5;
const BOLTZMANN_CONSTANT = 1.380649E-23;
const ENERGY_MULTIPLIER = BOLTZMANN_CONSTANT * 18;

export const AppConstants = {
    BUTTON_UPDATE_INTERVAL_DELAY,
    BUTTON_INCREMENT_DELAY,
    LOWEST_ENERGY_LEVEL,
    LOWEST_DEGENERACY,
    LOWEST_TEMPERATURE,
    LOWEST_LEVEL_COUNT,
    HIGHEST_ENERGY_LEVEL,
    HIGHEST_DEGENERACY,
    HIGHEST_TEMPERATURE,
    HIGHEST_LEVEL_COUNT,
    BOLTZMANN_CONSTANT,
    ENERGY_MULTIPLIER,
} as const;