const BUTTON_UPDATE_INTERVAL_DELAY = 500;
const BUTTON_INCREMENT_DELAY = 1;
const HIGHEST_MICROSTATE = 5;
const HIGHEST_TEMPERATURE = 1000;
const HIGHEST_DEGENERACY = 1;
const LOWEST_MICROSTATE = 0;
const LOWEST_TEMPERATURE = 0;
const LOWEST_MICROSTATE_COUNT = 2;
const LOWEST_DEGENERACY = 0;
const BOLTZMANN_CONSTANT = 1.380649E-23;
const ENERGY_MULTIPLIER = BOLTZMANN_CONSTANT * 18;

const AppConstants = {
    BUTTON_UPDATE_INTERVAL_DELAY,
    BUTTON_INCREMENT_DELAY,
    HIGHEST_MICROSTATE,
    HIGHEST_TEMPERATURE,
    HIGHEST_DEGENERACY,
    LOWEST_MICROSTATE,
    LOWEST_TEMPERATURE,
    LOWEST_MICROSTATE_COUNT,
    LOWEST_DEGENERACY,
    BOLTZMANN_CONSTANT,
    ENERGY_MULTIPLIER,
}

export default AppConstants;
