
const BUTTON_UPDATE_INTERVAL_DELAY = 500;
const BUTTON_INCREMENT_DELAY = 1;

const HIGHEST_ENERGY_LEVEL = 5;
const HIGHEST_TEMPERATURE = 1000;
const LOWEST_ENERGY_LEVEL = 0;
const LOWEST_TEMPERATURE = 0;
const LOWEST_LEVEL_COUNT = 2;
const ENERGY_MULTIPLIER = 18;

const AppConstants = {
    BUTTON_UPDATE_INTERVAL_DELAY,
    BUTTON_INCREMENT_DELAY,
    HIGHEST_ENERGY_LEVEL,
    HIGHEST_TEMPERATURE,
    LOWEST_ENERGY_LEVEL,
    LOWEST_TEMPERATURE,
    LOWEST_LEVEL_COUNT,
    ENERGY_MULTIPLIER,
}

export default AppConstants;
