
const HIGHEST_ENERGY_LEVEL = 5;
const HIGHEST_TEMPERATURE = 1_000_000;
const LOWEST_ENERGY_LEVEL = 0;
const LOWEST_TEMPERATURE = 0;

const SimulationContainer = {
    HIGHEST_ENERGY_LEVEL,
    HIGHEST_TEMPERATURE,
    LOWEST_ENERGY_LEVEL,
    LOWEST_TEMPERATURE,
};

export default SimulationContainer;
